apiVersion: v1
kind: Service
metadata:
  name: core-server-service
  namespace: mise-ai
spec:
  selector:
    app: core-server
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
