apiVersion: v1
kind: Service
metadata:
  name: ml-server-service
  namespace: mise-ai
spec:
  selector:
    app: ml-server
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
