/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesPlanningRouteImport } from './routes/sales/planning'
import { Route as SalesOverviewRouteImport } from './routes/sales/overview'
import { Route as PersonalSettingsRouteImport } from './routes/personal/settings'
import { Route as PersonalInsightsRouteImport } from './routes/personal/insights'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPlanningRoute = SalesPlanningRouteImport.update({
  id: '/sales/planning',
  path: '/sales/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOverviewRoute = SalesOverviewRouteImport.update({
  id: '/sales/overview',
  path: '/sales/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalSettingsRoute = PersonalSettingsRouteImport.update({
  id: '/personal/settings',
  path: '/personal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInsightsRoute = PersonalInsightsRouteImport.update({
  id: '/personal/insights',
  path: '/personal/insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/personal/insights': typeof PersonalInsightsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/sales/overview': typeof SalesOverviewRoute
  '/sales/planning': typeof SalesPlanningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/personal/insights': typeof PersonalInsightsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/sales/overview': typeof SalesOverviewRoute
  '/sales/planning': typeof SalesPlanningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/personal/insights': typeof PersonalInsightsRoute
  '/personal/settings': typeof PersonalSettingsRoute
  '/sales/overview': typeof SalesOverviewRoute
  '/sales/planning': typeof SalesPlanningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/personal/insights'
    | '/personal/settings'
    | '/sales/overview'
    | '/sales/planning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/personal/insights'
    | '/personal/settings'
    | '/sales/overview'
    | '/sales/planning'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/personal/insights'
    | '/personal/settings'
    | '/sales/overview'
    | '/sales/planning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PersonalInsightsRoute: typeof PersonalInsightsRoute
  PersonalSettingsRoute: typeof PersonalSettingsRoute
  SalesOverviewRoute: typeof SalesOverviewRoute
  SalesPlanningRoute: typeof SalesPlanningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/planning': {
      id: '/sales/planning'
      path: '/sales/planning'
      fullPath: '/sales/planning'
      preLoaderRoute: typeof SalesPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/overview': {
      id: '/sales/overview'
      path: '/sales/overview'
      fullPath: '/sales/overview'
      preLoaderRoute: typeof SalesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/settings': {
      id: '/personal/settings'
      path: '/personal/settings'
      fullPath: '/personal/settings'
      preLoaderRoute: typeof PersonalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/insights': {
      id: '/personal/insights'
      path: '/personal/insights'
      fullPath: '/personal/insights'
      preLoaderRoute: typeof PersonalInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PersonalInsightsRoute: PersonalInsightsRoute,
  PersonalSettingsRoute: PersonalSettingsRoute,
  SalesOverviewRoute: SalesOverviewRoute,
  SalesPlanningRoute: SalesPlanningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
