import type { ISale } from "./sales.domain";
import { TimeOfDay, WeatherCondition, SpecialEvent } from "./sales.domain";

export const salesMock: ISale[] = [
  {
    date: "2024-01-15",
    menu_item: "Grilled Chicken Sandwich",
    quantity_ordered: 50,
    quantity_sold: 45,
    quantity_wasted: 5,
    ingredient_cost: 6.5,
    selling_price: 14.99,
    total_revenue: 674.55,
    customer_count: 45,
    time_of_day: TimeOfDay.LUNCH,
    weather_condition: WeatherCondition.SUNNY,
    special_event: SpecialEvent.NONE,
    time_of_order: "2024-01-15T12:30:00Z",
  },
  {
    date: "2024-01-15",
    menu_item: "Caesar Salad",
    quantity_ordered: 30,
    quantity_sold: 28,
    quantity_wasted: 2,
    ingredient_cost: 4.25,
    selling_price: 11.99,
    total_revenue: 335.72,
    customer_count: 28,
    time_of_day: TimeOfDay.LUNCH,
    weather_condition: WeatherCondition.SUNNY,
    special_event: SpecialEvent.NONE,
    time_of_order: "2024-01-15T13:15:00Z",
  },
  {
    date: "2024-01-15",
    menu_item: "Ribeye Steak",
    quantity_ordered: 25,
    quantity_sold: 22,
    quantity_wasted: 3,
    ingredient_cost: 18.5,
    selling_price: 34.99,
    total_revenue: 769.78,
    customer_count: 22,
    time_of_day: TimeOfDay.DINNER,
    weather_condition: WeatherCondition.CLEAR,
    special_event: SpecialEvent.CHEF_SPECIAL,
    time_of_order: "2024-01-15T19:45:00Z",
  },
  {
    date: "2024-01-16",
    menu_item: "Pancake Stack",
    quantity_ordered: 40,
    quantity_sold: 35,
    quantity_wasted: 5,
    ingredient_cost: 3.75,
    selling_price: 9.99,
    total_revenue: 349.65,
    customer_count: 35,
    time_of_day: TimeOfDay.BREAKFAST,
    weather_condition: WeatherCondition.RAINY,
    special_event: SpecialEvent.WEEKEND_RUSH,
    time_of_order: "2024-01-16T08:30:00Z",
  },
  {
    date: "2024-01-16",
    menu_item: "Fish Tacos",
    quantity_ordered: 35,
    quantity_sold: 32,
    quantity_wasted: 3,
    ingredient_cost: 7.25,
    selling_price: 16.99,
    total_revenue: 543.68,
    customer_count: 32,
    time_of_day: TimeOfDay.LUNCH,
    weather_condition: WeatherCondition.CLOUDY,
    special_event: SpecialEvent.NONE,
    time_of_order: "2024-01-16T12:00:00Z",
  },
  {
    date: "2024-02-14",
    menu_item: "Lobster Thermidor",
    quantity_ordered: 20,
    quantity_sold: 18,
    quantity_wasted: 2,
    ingredient_cost: 24.5,
    selling_price: 49.99,
    total_revenue: 899.82,
    customer_count: 18,
    time_of_day: TimeOfDay.DINNER,
    weather_condition: WeatherCondition.CLEAR,
    special_event: SpecialEvent.VALENTINES_DAY,
    time_of_order: "2024-02-14T20:15:00Z",
  },
  {
    date: "2024-01-20",
    menu_item: "BBQ Burger",
    quantity_ordered: 60,
    quantity_sold: 55,
    quantity_wasted: 5,
    ingredient_cost: 5.5,
    selling_price: 13.99,
    total_revenue: 769.45,
    customer_count: 55,
    time_of_day: TimeOfDay.DINNER,
    weather_condition: WeatherCondition.SUNNY,
    special_event: SpecialEvent.FAMILY_DAY,
    time_of_order: "2024-01-20T18:30:00Z",
  },
  {
    date: "2024-01-31",
    menu_item: "Shrimp Scampi",
    quantity_ordered: 45,
    quantity_sold: 42,
    quantity_wasted: 3,
    ingredient_cost: 12.75,
    selling_price: 26.99,
    total_revenue: 1133.58,
    customer_count: 42,
    time_of_day: TimeOfDay.DINNER,
    weather_condition: WeatherCondition.CLEAR,
    special_event: SpecialEvent.PAYDAY_RUSH,
    time_of_order: "2024-01-31T19:00:00Z",
  },
];
